version: '3'
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
    - "./src:/app/src"
    ports:
    - "3000:3000"
    devices:
      - "/dev/video0:/dev/video0"

